2023-07-13 02:27:43 ERROR    discord.client Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/kyo/OAN/AVCB/lib/python3.10/site-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/kyo/OAN/cogs/ask.py", line 342, in on_message
    response = await asyncio.to_thread(chat.start, user_id, pass_question, new_language)
  File "/usr/local/lib/python3.10/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/kyo/OAN/bardapi/chat.py", line 42, in start
    self.initialize_bard(language)
  File "/home/kyo/OAN/bardapi/chat.py", line 28, in initialize_bard
    self.bard = Bard(
  File "/home/kyo/OAN/bardapi/core.py", line 55, in __init__
    self.SNlM0e = self._get_snim0e()
  File "/home/kyo/OAN/bardapi/core.py", line 229, in _get_snim0e
    resp = self.session.get(
  File "/home/kyo/OAN/AVCB/lib/python3.10/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/home/kyo/OAN/AVCB/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/kyo/OAN/AVCB/lib/python3.10/site-packages/requests/sessions.py", line 725, in send
    history = [resp for resp in gen]
  File "/home/kyo/OAN/AVCB/lib/python3.10/site-packages/requests/sessions.py", line 725, in <listcomp>
    history = [resp for resp in gen]
  File "/home/kyo/OAN/AVCB/lib/python3.10/site-packages/requests/sessions.py", line 191, in resolve_redirects
    raise TooManyRedirects(
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.

